language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"
preinstall:
  - npm config set package-lock false
deploy:
  provider: script
  script: npm install && gatsby build
  skip_cleanup: false
  on:
    branch: master
